apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jz1v4cn0x-go
  janus-idp.io/tekton: jz1v4cn0x-go
  backstage.io/kubernetes-id: jz1v4cn0x-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jz1v4cn0x-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
